### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by YuuLuo** [Equim-chan/Mortal#24]
![image](https://user-images.githubusercontent.com/69673808/197374543-0a312650-85f2-4901-907a-748045aee371.png)

Which kind of .json.gz dataset is required? I downloaded .json from majsoul and compressed to .gz but mortal can't read it.

**Comment by Equim-chan** [comment]
Read the doc, Mortal uses mjai everywhere.

**Comment by Lucas-Yang1** [comment]
I want to know how to get the dataset for training
