### ISSUE TITLE
1v3报错

### ISSUE THREAD

**Issue by YuuLuo** [Equim-chan/Mortal#26]
1v3的config设置为800 200时可以运行 但设置为2000 500时则报错 如图
![image](https://user-images.githubusercontent.com/69673808/200188458-e58faa1c-a27c-421f-8b86-3b6d30ad63db.png)

**Comment by Equim-chan** [comment]
应该是 akochan OOM 了，你检查下内存够不够用。

**Comment by YuuLuo** [comment]
好像是这样 在提升虚拟内存到1024000m 以及降低config到1200 300之后可以跑了 但是速度只有0.006setp/s  4090占用0% 只是在进行新一个step时会有很短的10%的占用
![image](https://user-images.githubusercontent.com/69673808/200191563-6df0fe84-0822-40a1-a3c2-de4b11912c30.png)

**Comment by Equim-chan** [comment]
正常，akochan 很慢而且很耗资源。
