### ISSUE TITLE
AssertionError: raw_count == S.buffer_size

### ISSUE THREAD

**Issue by hyskylord** [Equim-chan/Mortal#41]
在online训练时server.py偶尔会出现这个错误，目前移除了这个assert来使用但是不明白为什么会产生这个错误。所有程序均在本地运行。

**Comment by Equim-chan** [comment]
这个看起来像是有别人在往 buffer_dir 里写东西。

**Comment by Equim-chan** [comment]
在我的用法里，capacity 是比较小的，所以一直没有碰到这种情况

**Comment by hyskylord** [comment]
只要capacity>train_play.games就会出现这个问题，可以设置两者的值相等来避免。或者可以微调一下生成的文件名（如加入timestamp）从而避免覆写发生。
