### ISSUE TITLE
about q_values not match action type

### ISSUE THREAD

**Issue by teble** [Equim-chan/Mortal#44]
mortal 输出:
{'type': 'none', 'meta': {'q_values': [1.2168403, 0.33200026], 'mask_bits': 43980465111040, 'is_greedy': True, 'batch_size': 1, 'eval_time_ns': 39468600, 'shanten': 0, 'at_furiten': False}}

拆解mask_bists得到 (1<<43) | (1<<45)
对应q_values结果是 荣和 优先于 跳过，但是为什么mortal的实际操作却是跳过呢，本地运行mjai-reviewer运行结果下图所示
![image](https://user-images.githubusercontent.com/33313113/230721593-eee0705b-e8e5-4884-a4cf-69fdf810ffd8.png)

**Comment by Equim-chan** [comment]
Mortal 不完全是 end-to-end 的，它有一些 rule-based 策略。这里的情况是四确拒和，具体实现在 [libriichi/src/state/agent_helper.rs](https://github.com/Equim-chan/Mortal/blob/c2a9ea25a713bc716791cadff6b895b636e369e4/libriichi/src/state/agent_helper.rs#L272)。

要关闭这个功能的话，可以在创建 `MortalEngine` 时设置 `enable_rule_based_agari_guard=False`。

**Comment by teble** [comment]
> Mortal 不完全是 end-to-end 的，它有一些 rule-based 策略。这里的情况是四确拒和，具体实现在 [libriichi/src/state/agent_helper.rs](https://github.com/Equim-chan/Mortal/blob/c2a9ea25a713bc716791cadff6b895b636e369e4/libriichi/src/state/agent_helper.rs#L272)。
> 
> 要关闭这个功能的话，可以在创建 `MortalEngine` 时设置 `enable_rule_based_agari_guard=False`。

好的，感谢解答
