### ISSUE TITLE
关于数据集的格式

### ISSUE THREAD

**Issue by ZhiyuuuHa** [Equim-chan/Mortal#76]
请问要如何获取.json.gz形式的数据用以训练呢。我从天凤平台上下载了过去一年数据，都是.html.gz的后缀。.json.gz的数据是雀魂的对局数据吗

**Comment by Equim-chan** [comment]
Mortal 使用 mjai 格式，文档里有提到。

**Comment by ZhiyuuuHa** [comment]
是的我了解了，请问mjai格式的数据是需要手动转换还是通过别的方式获取呢
