### ISSUE TITLE
关于obs的编码构成

### ISSUE THREAD

**Issue by ZhiyuuuHa** [Equim-chan/Mortal#83]
我还未接触过rust语言，最近在尝试对mortal项目进行学习，看了一下对游戏状态进行encode的部分的代码。似乎是将手牌，鸣牌动作，宝牌等信息处理后进行编码，这样理解对吗？请问obs具体是如何构成的呢？
![obs](https://github.com/user-attachments/assets/d31a0eb9-2444-459f-ac23-b8f45fa1be5a)
![invisible_obs](https://github.com/user-attachments/assets/7d44d504-0a44-449b-b670-4c53e25c6aa6)

**Comment by hyskylord** [comment]
编码函数为encode_obs，可以在libriichi中查看。
