### ISSUE TITLE
是否有可能增加导出简易对局记录的选项

### ISSUE THREAD

**Issue by hyskylord** [Equim-chan/Mortal#86]
目前one_vs_three导出的对战记录包含了所有的q_value等模型信息，在研究阶段这些信息很有帮助，但是在大规模对局的时候这些信息显著增加了对局文件的大小（大概5到10倍）。希望能增加一个开关导出使得可以导出两种不同版本的对局记录。

**Comment by ttcwws** [comment]
请问mortal自战1v3的谱公布了吗，如果公布了在哪里呢，因为你说可以导出，好像是已经公布了的意思

**Comment by hyskylord** [comment]
> 请问mortal自战1v3的谱公布了吗，如果公布了在哪里呢，因为你说可以导出，好像是已经公布了的意思

这里指的是通过本地运行one_vs_three.py得到的牌谱

**Comment by Equim-chan** [comment]
应该不会特别追加这个选项，因为假设了存储资源是充足的。有需要的话可以自己修改代码。

**Comment by ttcwws** [comment]
大佬能公开4.1之间 1vs3的谱吗
